# Generated by Django 2.1.7 on 2019-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non Binary'), ('NOT_PROVIDED', 'Not Provided')], max_length=20, null=True)),
                ('email_id', models.CharField(max_length=200, unique=True)),
                ('ph_num', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CLIENT', 'Client'), ('APPROVER', 'Approver'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
