# Generated by Django 2.1.7 on 2019-03-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='fir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status_msg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='video',
            field=models.TextField(verbose_name='video source url'),
        ),
        migrations.AlterField(
            model_name='searcheesample',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
